# Generated by Django 5.2 on 2025-10-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Corte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("imagen", models.ImageField(upload_to="cortes/")),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Cortes",
                "ordering": ["-fecha_publicacion"],
            },
        ),
    ]
