# Generated by Django 5.2 on 2025-10-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformacionGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                (
                    "descripcion_corta",
                    models.CharField(
                        help_text="Descripción para la sección de encabezado.",
                        max_length=250,
                    ),
                ),
                (
                    "texto_principal",
                    models.TextField(
                        help_text="Texto largo para la sección 'Sobre Nosotros' o 'Nuestra Historia'."
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Información General",
                "verbose_name_plural": "Información General",
            },
        ),
        migrations.DeleteModel(
            name="Servicio",
        ),
    ]
