# Generated by Django 5.2 on 2025-10-14 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
                ("duracion_minutos", models.IntegerField(default=30)),
            ],
            options={
                "verbose_name_plural": "Servicios",
            },
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=100)),
                ("telefono_cliente", models.CharField(max_length=15)),
                ("fecha_hora", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("CON", "Confirmada"),
                            ("CAN", "Cancelada"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="citas.servicio"
                    ),
                ),
            ],
        ),
    ]
