# Generated by Django 5.2 on 2025-10-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicio",
            name="duracion_minutos",
        ),
        migrations.RemoveField(
            model_name="servicio",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="servicio",
            name="precio",
        ),
        migrations.AddField(
            model_name="cita",
            name="fecha_fin",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(),
        ),
    ]
