# Generated by Django 5.2 on 2025-10-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0002_remove_servicio_duracion_minutos_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cita",
            old_name="fecha_hora",
            new_name="fecha_hora_inicio",
        ),
        migrations.RemoveField(
            model_name="cita",
            name="fecha_fin",
        ),
        migrations.AddField(
            model_name="servicio",
            name="duracion_minutos",
            field=models.IntegerField(
                default=60, help_text="Duración del servicio en minutos"
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="nombre",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicio",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("CONFIRMADA", "Confirmada"),
                    ("CANCELADA", "Cancelada"),
                    ("COMPLETADA", "Completada"),
                ],
                default="PENDIENTE",
                max_length=10,
            ),
        ),
    ]
