# Generated by Django 5.2 on 2025-10-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0003_rename_fecha_hora_cita_fecha_hora_inicio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cita",
            name="servicio",
        ),
        migrations.AddField(
            model_name="cita",
            name="servicios",
            field=models.ManyToManyField(to="citas.servicio"),
        ),
    ]
