# Generated by Django 5.2 on 2025-10-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0005_cita_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Imagen representativa del servicio/producto",
                null=True,
                upload_to="servicios_imagenes/",
            ),
        ),
    ]
